### PR TITLE
Itinerary title functionality

### PR DESCRIPTION
**Pull request by cpilande**
### Description
This PR implements the itinerary title dialog that opens when the location button is clicked on the Itinerary Title Card in order to select which park the user will go to. 

### Motivation and Context
This PR is necessary to further broaden the functionality of the Itinerary Title Card. 

### Screenshots (if appropriate):
Screenshot 2023-11-26 at 4 42 03 PM

### Types of changes
- [ ]  Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ]  Refactoring (non-breaking change)
- [ ]  Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:
- [x] -  My code follows the code style of this project.
- [ ] -  My change requires a change to the documentation.
- [ ] -  I have updated the documentation accordingly.
- [ ] -  I have read the CONTRIBUTING document.
- [ ] -  I have added tests to cover my changes.

### CODE REVIEW

**Review by rdoinhs — APPROVED** [review]
Looks good.

**Review by heyitsmass — COMMENTED** [review]
Modals should implement a ReactPortal to property expose outside of the parent DOM

**Comment by cpilande** [comment]
> Modals should implement a ReactPortal to properly expose outside of the parent DOM
> 
> https://react.dev/reference/react-dom/createPortal

Headless UI library says it implements it for us: 
“Because of these accessibility concerns, Headless UI's Dialog component actually uses a Portal under-the-hood. This way we can provide features like unobstructed event handling and making the rest of your application inert. So, when using our Dialog, there's no need to use a Portal yourself! We've already taken care of it.”
https://headlessui.com/react/dialog#

**Review by heyitsmass — APPROVED** [review]

**Comment by heyitsmass** [comment]
> > Modals should implement a ReactPortal to properly expose outside of the parent DOM
> > https://react.dev/reference/react-dom/createPortal
> 
> Headless UI library says it implements it for us: “Because of these accessibility concerns, Headless UI's Dialog component actually uses a Portal under-the-hood. This way we can provide features like unobstructed event handling and making the rest of your application inert. So, when using our Dialog, there's no need to use a Portal yourself! We've already taken care of it.” https://headlessui.com/react/dialog#

image

**Pull request merged**
